#!/bin/sh

# Example for $XDG_CONFIG_HOME/sxiv/exec/key-handler
# Called by sxiv(1) after the external prefix key (C-x by default) is pressed.
# The next key combo is passed as its first argument. Passed via stdin are the
# images to act upon, one path per line: all marked images, if in thumbnail
# mode and at least one image has been marked, otherwise the current image.
# sxiv(1) blocks until this script terminates. It then checks which images
# have been modified and reloads them.

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.

while read file ; do
    echo Running on $file
    ext=$(echo $file | sed 's/.*\.//')
    filename=$(echo $file | sed 's/.*\/\(.*\)\..*/\1/')
    path=$(echo $file | sed 's/\(.*\/\).*/\1/')
    case "$1" in
    "d")      mv "$file" ~/.trash ;;
    "x")      echo "$file" | xclip -in -selection clipboard ;;
    "y")      xclip -selection clipboard -target image/png "$file" ;;
    "k")      krita --nosplash "$file" & disown ;;
    "U")      waifu_upscale_2x.sh "$file" ;;
    "j")      convert "$file" "$path$filename.jpg"; mv "$file" ~/.trash ;;
    # "comma")  rotate 270 "$1" ;;
    # "period") rotate  90 "$1" ;;
    # "slash")  rotate 180 "$1" ;;
    esac
done
